---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "segger"
description: Train a Segger cell segmentation model using a segger-created dataset.
keywords:
  - segmentation
  - xenium
  - imaging
  - model-training
tools:
  - "segger":
      description: "Segger uses graph neural networks and heterogeneous graphs to offer efficient cell segmentation at unmatched precision and accuracy."
      homepage: "https://github.com/EliHei2/segger_dev"
      documentation: "https://elihei2.github.io/segger_dev/user_guide/"
      tool_dev_url: "https://github.com/EliHei2/segger_dev"
      doi: "tbd"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - dataset_dir:
      type: file
      description: |
        Directory where the processed dataset is stored for training.
  - models_dir:
      type: directory
      description: |
        Directory to save the trained model and checkpoints.

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@tobiaspk"
maintainers:
  - "@tobiaspk"
