name: xeniumranger_resegment
description: The xeniumranger resegment module allows you to generate a new segmentation of the morphology image space by rerunning the Xenium Onboard Analysis (XOA) segmentation algorithms with modified parameters.
keywords:
  - spatial
  - resegment
  - morphology
  - segmentation
  - xeniumranger
tools:
  - xeniumranger:
      description: |
        Xenium Ranger is a set of analysis pipelines that process Xenium In Situ Gene Expression data to relabel, resegment, or import new segmentation results from community-developed tools. Xenium Ranger provides flexible off-instrument reanalysis of Xenium In Situ data. Relabel transcripts, resegment cells with the latest 10x segmentation algorithms, or import your own segmentation data to assign transcripts to cells.
      homepage: "https://www.10xgenomics.com/support/software/xenium-ranger/latest"
      documentation: "https://www.10xgenomics.com/support/software/xenium-ranger/latest/getting-started"
      tool_dev_url: "https://www.10xgenomics.com/support/software/xenium-ranger/latest/analysis"
      licence:
        - "10x Genomics EULA"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing run information
          e.g. [ id:'xenium_experiment' ]
    - xenium_bundle:
        type: directory
        description: Path to the xenium output bundle generated by the Xenium Onboard Analysis pipeline

output:
  - bundle:
      - meta:
          type: file
          description: Files containing the outputs of Cell Ranger, see official 10X Genomics documentation for a complete list
          pattern: "${meta.id}/outs/*"
      - "${meta.id}/outs":
          type: file
          description: Files containing the outputs of xenium ranger, see official 10X Genomics documentation for a complete list of outputs
          pattern: "${meta.id}/outs/*"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@khersameesh24"
maintainers:
  - "@khersameesh24"
